apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: non-root-pod
  name: non-root-pod
spec:
  containers:
  - image: redis:alpine
    name: non-root-pod
    resources: {}
  securityContext:
    fsGroup: 2000
    runAsUser: 1000
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
